// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TADS_Web.Models.DB;

#nullable disable

namespace TADS_Web.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20260707164601_AddTbAboutContent")]
    partial class AddTbAboutContent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TADS_Web.Models.DB.TbAboutContent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("BoardDirectors")
                        .HasColumnType("TEXT");

                    b.Property<string>("BoardExecDirectors")
                        .HasColumnType("TEXT");

                    b.Property<string>("BoardExecSecretary")
                        .HasColumnType("TEXT");

                    b.Property<string>("BoardExecSupervisor")
                        .HasColumnType("TEXT");

                    b.Property<string>("BoardPresident")
                        .HasColumnType("TEXT");

                    b.Property<string>("BoardSecretaryGeneral")
                        .HasColumnType("TEXT");

                    b.Property<string>("BoardSupervisors")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BoardTermNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BoardVicePresident")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConstitutionPdfFileId")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConstitutionText")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("IntroDetail")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntroImageFileId")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("IntroNameEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntroNameZh")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntroSummary")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberResearchDesc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MembershipInviteEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("MembershipInviteZh")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrgChartFileId")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("PastBoardListUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("PK_TbAboutContent");

                    b.ToTable("TbAboutContent");
                });

            modelBuilder.Entity("TADS_Web.Models.DB.TbAboutPricing", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("DescEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescZh")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEn")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NameZh")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Price")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("PK_TbAboutPricing");

                    b.ToTable("TbAboutPricing");
                });

            modelBuilder.Entity("TADS_Web.Models.DB.TbAnnualMeeting", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<string>("Contents")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublish")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TbAnnualMeeting");
                });

            modelBuilder.Entity("TADS_Web.Models.DB.TbApiLog", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ipaddr")
                        .HasMaxLength(45)
                        .HasColumnType("TEXT")
                        .HasColumnName("IPAddr");

                    b.Property<string>("Request")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoutePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Pid")
                        .HasName("PK_API_Log");

                    b.ToTable("TbApiLog");
                });

            modelBuilder.Entity("TADS_Web.Models.DB.TbBackendOperateLog", b =>
                {
                    b.Property<long>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PID");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DataKey")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Feature")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("IP");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Request")
                        .HasColumnType("TEXT");

                    b.Property<string>("Response")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("UserID");

                    b.HasKey("Pid")
                        .HasName("PK_TbOperateLog");

                    b.ToTable("TbBackendOperateLog");
                });

            modelBuilder.Entity("TADS_Web.Models.DB.TbBanner", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileId")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("FileID");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublish")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TbBanner");
                });

            modelBuilder.Entity("TADS_Web.Models.DB.TbFileInfo", b =>
                {
                    b.Property<string>("FileId")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("FileID");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileDescription")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePathM")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePathS")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileRealName")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<byte?>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("FileId")
                        .HasName("PK_TB_FileInfo");

                    b.ToTable("TbFileInfo");
                });

            modelBuilder.Entity("TADS_Web.Models.DB.TbIdSummary", b =>
                {
                    b.Property<string>("TableName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<long>("MaxId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("MaxID");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TableName")
                        .HasName("PK_TbIdSummary_1");

                    b.ToTable("TbIdSummary");
                });

            modelBuilder.Entity("TADS_Web.Models.DB.TbLog", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PID");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("IP");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Pid")
                        .HasName("PK_TB_LoginRecord");

                    b.ToTable("TbLog");
                });

            modelBuilder.Entity("TADS_Web.Models.DB.TbLoginRecord", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PID");

                    b.Property<string>("Account")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Inputaua8")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ip")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("IP");

                    b.Property<string>("LoginMsg")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("MemberId")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("MemberID");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Sso")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SSO");

                    b.Property<string>("Ssoresult")
                        .HasColumnType("TEXT")
                        .HasColumnName("SSOResult");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("UserID");

                    b.HasKey("Pid")
                        .HasName("PK_TB_S_LoginRecord");

                    b.ToTable("TbLoginRecord");
                });

            modelBuilder.Entity("TADS_Web.Models.DB.TbMemberResearch", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<string>("AuthorBioExpertise")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorBioName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorBioPosition")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthorInfo")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Citation")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileId")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("FileID");

                    b.Property<string>("IntroContent")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntroTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublish")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TbMemberResearch");
                });

            modelBuilder.Entity("TADS_Web.Models.DB.TbNews", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("ID");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Contents")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateUser")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DisplayDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileId")
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasColumnName("FileID");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsKeepTop")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublish")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TbNews");
                });

            modelBuilder.Entity("TADS_Web.Models.DB.TbPageContent", b =>
                {
                    b.Property<string>("PageCode")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Contents")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreateUser")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifyDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModifyUser")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("PageCode")
                        .HasName("PK_TbPageContent");

                    b.ToTable("TbPageContent");
                });

            modelBuilder.Entity("TADS_Web.Models.DB.TbUser", b =>
                {
                    b.Property<int>("Pid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("PID");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Pid")
                        .HasName("PK_TbUser");

                    b.HasIndex("Account")
                        .IsUnique();

                    b.ToTable("TbUser");
                });
#pragma warning restore 612, 618
        }
    }
}
